image: livexp/android-sdk

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build

before_script:
    - docker-android-sdk-install "build-tools;28.0.3"
    - cd /root/
    - wget https://services.gradle.org/distributions/gradle-5.3-bin.zip > /dev/null 2>&1
    - unzip gradle-5.3-bin.zip > /dev/null 2>&1
    - cd -

build_release_app:
  stage: build
  only:
    refs:
      - release
  artifacts:
    paths:
      - app/build/outputs/apk/normal/release/app-normal-release-unsigned.apk
  script:
      - export PATH=/root/gradle-5.3/bin:$PATH
      - pwd
      - cd app ; gradle assembleNormal

build_dev_app:
  stage: build
  only:
    refs:
      - build
  artifacts:
    paths:
      - app/build/outputs/apk/dev/debug/app-dev-debug.apk
  script:
      - export PATH=/root/gradle-5.3/bin:$PATH
      - pwd
      - cd app ; gradle assembleDev

